sudo: required
language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - sys-img-x86-android-28
before_install:
 - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-28"
before_script:
 - echo no | android create avd --force -n test -t android-28 --abi x86
 - emulator -avd test -no-audio -no-window &
 - android-wait-for-emulator
 - chmod +x gradlew
 - chmod +x generate-apks.sh
script:
 - ./gradlew build
 - ./gradlew clean build connectedAndroidTest
after_success:
 - ./generate-apks.sh
